spring:
  cloud:
    azure:
      credential:
        managed-identity-enabled: true
      storage:
        blob:
          account-name: <Storage Account Name>
          container-name: <Container Name>
          endpoint: <Storage Endpoint>
          
